Fix the issue TypeError: YouTube.vid_info_client.<locals>.call_innertube() missing 1 required positional argument: 'optional_client'
Fix the issue `TypeError: YouTube.vid_info_client.<locals>.call_innertube() missing 1 required positional argument: 'optional_client'` https://github.com/JuanBindez/pytubefix/issues/546